name: ida-sigmaker tests

on:
    push:
        branches:
            - "main"
    pull_request:
        types:
            - synchronize
            - opened
            - reopened
            - ready_for_review
        branches:
            - "main"

# cancel previous workflow jobs for PRs
concurrency:
    group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.run_id }}
    cancel-in-progress: true

jobs:
    unit-tests:
        runs-on: ubuntu-24.04
        strategy:
            matrix:
                python-version: ["3.13"]
        env:
            PYTHONPATH: ${{ github.workspace }}
        steps:
            - name: "Checkout ${{ github.ref }} ( ${{ github.sha }} )"
              uses: actions/checkout@v4
              with:
                  persist-credentials: false
            - name: Set up Python${{ matrix.python-version }}
              uses: actions/setup-python@v5
              with:
                  python-version: ${{ matrix.python-version }}
                  cache: "pip"
            - name: Login to GHCR (only if private)
              uses: docker/login-action@v3
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.GHCR_TOKEN }}

            - name: Try logging in to GHCR
              run: |
                  echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

            - name: Run test_sigmaker.py
              run: |
                  docker compose run --rm idapro-tests test_sigmaker.py ||  { docker compose logs idapro-tests ; exit 1 ; }
                  docker compose logs idapro-tests
